# Generated by Django 4.2.2 on 2023-07-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=1500)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=15000)),
                ('fb_tink', models.URLField()),
                ('twitter_link', models.URLField()),
                ('instagram_link', models.URLField()),
            ],
        ),
    ]
