# Generated by Django 4.2.2 on 2023-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.TextField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
