# Generated by Django 4.2.2 on 2023-07-05 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
