# Generated by Django 4.2.2 on 2023-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_alter_propertybook_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='children',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=2),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='guest',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=2),
        ),
    ]
