# Generated by Django 4.2.2 on 2023-07-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_alter_propertybook_children_alter_propertybook_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
